
name: Deploy WordPress to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Add commands to install dependencies
          # e.g., npm install

      - name: Build project
        run: |
          # Add commands to build the project
          # e.g., npm run build

      - name: Transfer files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "https://github.com/nileshsurya1994/wordpress.git"
          target: "/var/www/html/wordpress"

